name: ros_dart
description: ROS implementation directly porting rosbridge_client_dot_net package to dart
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.24.2
  very_good_analysis: ^5.0.0
