name: ros_dart
description: ROS implementation directly porting rosbridge_client_dot_net package to dart
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  web_socket_client: ^0.1.0-dev.3
dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
